name: my-composite

# inputs:
#   # Pass ${{ github.repository }} here
#   target-repo:
#     description: "AAAAAAAAAAAA"
#     required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      # with:
      #   repository: "${{ inputs.target-repo }}"
    - name: Write to readme
      shell: bash
      run: echo "BBBBBBBBBBBBB" >> README.md
    - name: Save updates
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Add BBBBBBBBBBBBB to README
