name: my-composite

inputs:
  ignore:
    description: "Ignored repos"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Setup Golang caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run README generator
      shell: bash
      run: 'export ORIGIN_REPO="$PWD" && (cd $GITHUB_ACTION_PATH && go run ./main.go -file=$ORIGIN_REPO/README.md -owner=${{ github.repository_owner }} -ignore=${{ inputs.ignore }})'
    - name: Save updates
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Add CCCCCCCCCC to README
