name: my-composite

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run README generator
      shell: bash
      run: |
        export ORIGIN_REPO="$PWD"
        (cd $GITHUB_ACTION_PATH && go run ./main.go -- $ORIGIN_REPO README.md)
    - name: Save updates
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Add CCCCCCCCCC to README
